version: '3.7'

services:
  client0xkid:
    build:
      context: .
      dockerfile: Dockerfile
    image: client0xkid
    container_name: client0xkid
    volumes:
      - ./client0xkid/:/usr/app
      - /usr/app/node_modules
    ports:
      - "5173:5173"

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local