version: '3.7'

services:
  proxima:
    build:
      context: .
      dockerfile: Dockerfile
    image: proxima
    container_name: proxima
    volumes:
      - ./client0xkid/:/usr/app
      - /usr/app/node_modules
    ports:
      - "5173:5173"

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local