version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: 0xkidserver
    container_name: 0xkidserver
    command: npm start
    volumes:
      - ./0xkidserver/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT="${PORT}"
      - MONGO_URI="${MONGO_URI}"
    networks:
      - 0xkid-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: 0xkidclient
    container_name: 0xkidclient
    command: npm run dev
    volumes:
      - ./0xkidclient/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "5173:5173"
    networks:
      - 0xkid-network

networks:
    0xkid-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
