version: '3.7'

services:
  server0xkid:
    build:
      context: .
      dockerfile: Dockerfile
    image: server0xkid
    container_name: server0xkid
    # command: npm start
    volumes:
      - ./server0xkid/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"


volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local