version: '3.7'

services:
  proxima-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: proxima-server
    container_name: proxima-server
    volumes:
      - ./server0xkid/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"


volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local